name: ESLint (Next.js + Express)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: ${{ matrix.part }} / ${{ matrix.os }} / Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]
        part: [app, server]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (app)
        if: matrix.part == 'app'
        run: npm run lint # TODO: seperate linting for server and app.
        shell: bash

      - name: Run ESLint (server)
        if: matrix.part == 'server'
        run: npm run lint # TODO: seperate linting for server and app.
        shell: bash
